name: CI

on: 
  pull_request:
    branches: [main, develop]

jobs: 
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Lint SQL
        run: |
            pip install sqlfluff
            sqlfluff lint leetcode/ --config .sqlfluff